services:
  elemental:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    env_file: ".env"
    # volumes:
    #   - .:/app
    # environment:
    #   - ENV=development
